services:
  dataportal-backend:
    image: ghcr.io/actris-cloudnet/dataportal-backend
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ../dataportal-fixtures:/dataportal-fixtures
      - ../backend-fixtures:/backend-fixtures
    env_file:
      - test.env
    environment:
      - SS_MODE=remote
    command:
      [
        "sh",
        "-c",
        "node build/fixtures.js /backend-fixtures/backend/fixtures TRUNCATE && node build/fixtures.js /dataportal-fixtures APPEND && npm run start",
      ]
  db:
    image: "postgres:16"
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "54321:54321"
    environment:
      TZ: "Europe/Helsinki"
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGUSER: admin
    healthcheck:
      test: ["CMD", "psql", "-c", "select 1"]
      interval: 1s
      retries: 120
  moto-server:
    image: "motoserver/moto:3.0.1"
  storage-service:
    image: ghcr.io/actris-cloudnet/storage-service
    ports:
      - "5900:5900"
    depends_on:
      db:
        condition: service_healthy
      moto-server:
        condition: service_started
    environment:
      - NODE_ENV=test
      - SS_USER=test
      - SS_PWHASH=9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08
      - SS_MAXOBJECTSPERBUCKET=10000
      - PGHOST=db
      - PGDATABASE=ss
      - PGUSER=ss
      - PGPASSWORD=dev
      - S3_ENDPOINT=http://moto-server:5000
      - S3_ACCESSKEYID=dev
      - S3_SECRETACCESSKEY=dev
      - S3_FORCE_PATH_STYLE=true
    command: ["sh", "-c", "node build/init.js && npm start"]
