name: Test and lint

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    timeout-minutes: 5
    strategy:
      matrix:
        python-version: ["3.10", "3.14"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: pyproject.toml

      - name: Checkout fixtures
        uses: actions/checkout@v6
        with:
          repository: actris-cloudnet/dataportal
          sparse-checkout: backend/fixtures/
          sparse-checkout-cone-mode: false
          path: backend-fixtures

      - name: Checkout production fixtures
        uses: actions/checkout@v6
        with:
          repository: actris-cloudnet/dataportal-fixtures
          path: dataportal-fixtures

      - name: Start dataportal
        run: docker compose -f .github/docker-compose.yml up -d --wait

      - name: Install dependencies
        run: pip install .[dev,test]

      - name: Run pre-commit checks
        if: matrix.python-version == '3.14'
        run: pre-commit run --all-files --show-diff-on-failure

      - name: Run tests
        run: pytest -s -vv

      - name: Shutdown backend
        if: always()
        run: docker compose -f .github/docker-compose.yml down

      - name: Print logs
        if: always()
        run: docker compose -f .github/docker-compose.yml logs
